# Generated by Django 4.2.6 on 2024-04-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('pass_fail', models.BooleanField()),
                ('number_of_attempts', models.IntegerField()),
                ('words_guessed', models.TextField(help_text='Comma-separated list of guessed words')),
                ('correct_word', models.CharField(max_length=100)),
            ],
        ),
    ]
